#!/usr/bin/env python3
"""Standalone post-merge closeout command for the Feature Factory runner.

Usage:
    run_factory.py closeout --slug SLUG [--pr-url URL] [--pr-number N]
                            [--merge-sha SHA] [--note "..."] [--out PATH]

Run this after ``gh pr merge`` to record delivery state, write a
``closeout.md`` with a Review Coverage table, and tick confirmed-merged
slice checkboxes in ``tasks.md``.

This command is intentionally decoupled from the rest of the FF flow — it
works regardless of whether the run used full / quick / none mode and does
not require passing CI checks.  Operators run it once after merge to close
out a run cleanly.
"""
import argparse
import datetime
import json
import re
import subprocess
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from factory_state import (  # noqa: E402
    DELIVERY_KEY,
    load_workflow_state,
    save_workflow_state,
    workflow_dir,
    reviews_dir,
)
from factory_mutating import mutates_state  # noqa: E402

# ---------------------------------------------------------------------------
# Lens definitions — what each stage's default review set looks like.
# Used to compute "skipped" entries (default lenses not found in reviews/).
# Matches factory_review_specs.required_reviews() defaults.
# ---------------------------------------------------------------------------

_STAGE_DEFAULT_LENSES: dict[str, list[str]] = {
    "spec": [
        "codex:feasibility-adversarial",
        "gemini:requirements-adversarial",
    ],
    "plan": [
        "codex:implementation-adversarial",
        "gemini:testability-adversarial",
    ],
    "tasks": [],
    "diff": [],
    "closeout": [],
}

# Pattern for review filenames: <stage>.<reviewer>.<lens>.review.md
_REVIEW_FILENAME_RE = re.compile(
    r"^(?P<stage>[^.]+)\.(?P<reviewer>[^.]+)\.(?P<lens>.+)\.review\.md$"
)

# Marker for the generated section in closeout.md
_GEN_START = "<!-- Generated by run_factory.py closeout. Edit below the marker line. -->"
_GEN_END = "<!-- end-generated -->"

# Markers for the Run Facts sub-section (nested inside the generated block)
_RUN_FACTS_START = "<!-- begin-run-facts -->"
_RUN_FACTS_END = "<!-- end-run-facts -->"

# Known ordered stages (used to derive "skipped" stages)
_KNOWN_STAGES = ["spec", "plan", "tasks", "diff", "closeout"]

# Strings emitted by factory_telemetry._parse_error when a successful call
# returned output the parser couldn't extract token counts from. These are
# telemetry parse gaps, NOT call failures — exclude from Run Facts error
# counts. Source of truth: factory_telemetry.py:_parse_error.
_TELEMETRY_PARSE_GAPS = frozenset({
    "no Codex token block found in stderr",
    "no Claude token counts found in stdout or stderr",
    "no Gemini token stats found in stdout",
})


def _is_real_call_error(parse_error: object) -> bool:
    """True if parse_error indicates a real call failure (not a token-parse gap).

    factory_telemetry records parse_error for two distinct reasons:
    1. The subprocess actually failed (timeout, non-zero exit, etc.) — real error.
    2. The subprocess succeeded but stderr/stdout didn't contain the expected
       token-count block — telemetry gap, not a call failure.

    Run Facts surfaces #1 as errors and ignores #2. Mixing them produces
    misleading reports like "25 errors" when the calls all succeeded but the
    token parser didn't find counts.
    """
    if not parse_error or not isinstance(parse_error, str):
        return False
    return parse_error not in _TELEMETRY_PARSE_GAPS


# Checkbox patterns in tasks.md
_OPEN_CHECKBOX_RE = re.compile(r"^\s*[-*]\s+\[ \]")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _iso_now() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")


def _detect_pr_from_gh(branch_hint: str) -> dict:
    """Try to detect PR info via gh CLI. Returns partial dict on failure."""
    result: dict = {}
    try:
        proc = subprocess.run(
            ["gh", "pr", "list", "--search", f"head:{branch_hint}", "--json",
             "number,url,mergeCommit,state"],
            capture_output=True, text=True, timeout=30,
        )
        if proc.returncode != 0:
            return result
        items = json.loads(proc.stdout or "[]")
        if not items:
            return result
        # Prefer merged or closed PR
        for item in items:
            pr_state = str(item.get("state", "")).upper()
            if pr_state in ("MERGED", "CLOSED"):
                result["pr_number"] = item.get("number")
                result["pr_url"] = item.get("url", "")
                mc = item.get("mergeCommit")
                if isinstance(mc, dict):
                    result["merge_sha"] = mc.get("oid", "")
                elif isinstance(mc, str):
                    result["merge_sha"] = mc
                return result
        # Fallback: first open PR
        item = items[0]
        result["pr_number"] = item.get("number")
        result["pr_url"] = item.get("url", "")
    except Exception:  # noqa: BLE001
        pass
    return result


def _slug_to_branch(slug: str) -> str:
    """Derive a probable branch name from the slug."""
    return f"claude/{slug}"


def _scan_reviews(slug: str) -> dict[str, set[str]]:
    """Return {stage: set_of_lens_keys} from reviews directory.

    A lens key is ``reviewer:lens`` e.g. ``codex:correctness-adversarial``.
    """
    rdir = reviews_dir(slug)
    found: dict[str, set[str]] = {}
    if not rdir.exists():
        return found
    for path in rdir.iterdir():
        m = _REVIEW_FILENAME_RE.match(path.name)
        if not m:
            continue
        stage = m.group("stage")
        reviewer = m.group("reviewer")
        lens = m.group("lens")
        key = f"{reviewer}:{lens}"
        found.setdefault(stage, set()).add(key)
    return found


def _build_review_coverage(
    review_map: dict[str, set[str]],
    token_usage: list[dict],
) -> dict:
    """Compute review_coverage_summary across all tracked stages."""
    stages = ["spec", "plan", "tasks", "diff", "closeout"]
    summary: dict = {}
    for stage in stages:
        default_lenses = set(_STAGE_DEFAULT_LENSES.get(stage, []))
        found_lenses = review_map.get(stage, set())

        # Also pull lenses recorded in token_usage (belt-and-suspenders)
        for entry in token_usage:
            if entry.get("stage") != stage:
                continue
            if entry.get("activity_type") != "adversarial_review":
                continue
            lens_val = entry.get("lens", "")
            model = entry.get("model", "")
            if not lens_val:
                continue
            reviewer = "gemini" if "gemini" in model else "codex"
            found_lenses.add(f"{reviewer}:{lens_val}")

        run_list = sorted(found_lenses)
        # skipped = default lenses not found anywhere in the run
        skipped_list = sorted(default_lenses - found_lenses)
        summary[stage] = {
            "lenses_run": run_list,
            "lenses_skipped": skipped_list,
        }
    return summary


def _coverage_table_text(coverage: dict) -> str:
    """Render the Review Coverage table from coverage summary dict."""
    lines = [
        "| Stage | Lenses run | Lenses skipped |",
        "| --- | --- | --- |",
    ]
    for stage in ["spec", "plan", "tasks", "diff", "closeout"]:
        data = coverage.get(stage, {})
        run = ", ".join(data.get("lenses_run", [])) or "—"
        skipped = ", ".join(data.get("lenses_skipped", [])) or "—"
        lines.append(f"| {stage} | {run} | {skipped} |")
    return "\n".join(lines)


def _tick_merged_slices(tasks_path: Path) -> bool:
    """Tick open checkboxes in tasks.md for slices that appear to be done.

    Conservative rule: tick a checkbox only if it immediately precedes a line
    containing ``[CHECKPOINT]`` (i.e., it is a slice boundary line). This is
    a rough proxy — the real record is in state.json, but for the manual
    post-merge case we only tick lines that look like completed checkpoints.

    Returns True if any change was made.
    """
    if not tasks_path.exists():
        return False
    text = tasks_path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    changed = False
    for idx, line in enumerate(lines):
        if "[CHECKPOINT]" in line and _OPEN_CHECKBOX_RE.match(line):
            # Tick the checkbox
            lines[idx] = line.replace("[ ]", "[x]", 1)
            changed = True
    if changed:
        tasks_path.write_text("".join(lines), encoding="utf-8")
    return changed


def _fmt_duration(total_seconds: float) -> str:
    """Format a duration in seconds as 'Hh Mm' (or 'Mm Ss' if under 1 hour)."""
    total_seconds = max(0.0, total_seconds)
    total_int = int(round(total_seconds))
    hours = total_int // 3600
    minutes = (total_int % 3600) // 60
    seconds = total_int % 60
    if hours > 0:
        return f"{hours}h {minutes:02d}m"
    return f"{minutes}m {seconds:02d}s"


def _parse_iso(ts: str) -> float | None:
    """Parse an ISO-8601 timestamp string to a POSIX float. Returns None on failure."""
    if not ts or not isinstance(ts, str):
        return None
    # Normalise trailing Z to +00:00 for fromisoformat compatibility
    normalised = ts.replace("Z", "+00:00")
    try:
        return datetime.datetime.fromisoformat(normalised).timestamp()
    except (ValueError, OverflowError):
        return None


def _build_run_facts_text(token_usage: list[dict], codex_dispatches: list[dict]) -> str:
    """Build the body text between the <!-- begin-run-facts --> markers.

    Strategy for per-stage wall clock: we use max(ended_at) - min(started_at) per
    stage rather than summing individual durations. This gives the elapsed calendar
    time spent in each stage including any idle gaps (operator review, re-runs within
    a stage). It more accurately represents "how long was the runner working on this
    stage" from a run-time perspective.

    Codex timeouts: we rely on parse_error containing "timeout" rather than
    duration_seconds >= 119 because the dispatch subcommand raises SystemExit(5) on
    timeout — those calls never produce a token_usage entry at all. Token-usage entries
    near 119s are simply slow successful calls.  Within token_usage, "timeout" in
    parse_error is the reliable signal.

    Codex dispatches retry detection: we group by prompt_sha256 (same prompt re-run)
    since there is no slice_id field in the codex_dispatches schema. Groups with
    >1 entry are retries.
    """
    if not token_usage:
        lines = [
            _RUN_FACTS_START,
            "",
            "Run had no recorded subprocess activity.",
            "",
            _RUN_FACTS_END,
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Wall clock
    # ------------------------------------------------------------------
    all_starts = [_parse_iso(e.get("started_at", "")) for e in token_usage]
    all_ends = [_parse_iso(e.get("ended_at", "")) for e in token_usage]
    valid_starts = [t for t in all_starts if t is not None]
    valid_ends = [t for t in all_ends if t is not None]

    if valid_starts and valid_ends:
        total_seconds = max(valid_ends) - min(valid_starts)
        total_str = _fmt_duration(total_seconds)
    else:
        total_str = "(no data)"

    # Per-stage wall clock
    stage_times: dict[str, str] = {}
    for stage in _KNOWN_STAGES:
        entries = [e for e in token_usage if e.get("stage") == stage]
        if not entries:
            continue
        starts = [t for t in (_parse_iso(e.get("started_at", "")) for e in entries) if t is not None]
        ends = [t for t in (_parse_iso(e.get("ended_at", "")) for e in entries) if t is not None]
        if starts and ends:
            stage_times[stage] = _fmt_duration(max(ends) - min(starts))

    if stage_times:
        per_stage_parts = [f"{stage} {stage_times[stage]}" for stage in _KNOWN_STAGES if stage in stage_times]
        per_stage_str = " · ".join(per_stage_parts)
    else:
        per_stage_str = "(no data)"

    # ------------------------------------------------------------------
    # Subprocess call counts
    # ------------------------------------------------------------------
    codex_entries = [
        e for e in token_usage
        if (e.get("model") or "").startswith(("gpt-", "codex-"))
    ]
    gemini_entries = [
        e for e in token_usage
        if (e.get("model") or "").startswith("gemini-")
    ]

    codex_total = len(codex_entries)
    gemini_total = len(gemini_entries)

    # Three distinct categories of parse_error:
    #   1. timeout — call hit the subprocess timeout
    #   2. telemetry parse gap — call succeeded, parser couldn't extract token counts
    #   3. other / real errors — anything else recorded as parse_error
    # We surface all three separately so a flood of telemetry gaps doesn't get
    # mistaken for real failures, and a flood of real failures doesn't get
    # buried in noise.
    codex_timeouts = sum(
        1 for e in codex_entries
        if "timeout" in (e.get("parse_error") or "").lower()
    )
    codex_parse_gaps = sum(
        1 for e in codex_entries
        if (e.get("parse_error") or "") in _TELEMETRY_PARSE_GAPS
    )
    codex_other_errors = sum(
        1 for e in codex_entries
        if _is_real_call_error(e.get("parse_error"))
        and "timeout" not in (e.get("parse_error") or "").lower()
    )

    gemini_parse_gaps = sum(
        1 for e in gemini_entries
        if (e.get("parse_error") or "") in _TELEMETRY_PARSE_GAPS
    )
    gemini_errors = sum(
        1 for e in gemini_entries
        if _is_real_call_error(e.get("parse_error"))
    )

    # ------------------------------------------------------------------
    # Codex dispatch slices and retries
    # ------------------------------------------------------------------
    if codex_dispatches:
        # Group by prompt_sha256 (same prompt content = same logical slice).
        # Entries without prompt_sha256 are placed in a fallback group per ts.
        groups: dict[str, list[dict]] = {}
        for d in codex_dispatches:
            key = d.get("prompt_sha256") or d.get("ts", "unknown")
            groups.setdefault(key, []).append(d)

        total_slices = len(groups)
        retry_groups = {k: v for k, v in groups.items() if len(v) > 1}
        retry_count = len(retry_groups)

        if retry_count > 0:
            # Build per-retry description using the first dispatch's ts as a label
            retry_parts = []
            for i, (_, attempts) in enumerate(sorted(retry_groups.items(), key=lambda kv: kv[1][0].get("ts", ""))):
                label = f"slice {i + 1}"
                retry_parts.append(f"{label}: {len(attempts)} attempts")
            retry_detail = "; ".join(retry_parts)
            dispatches_str = f"{total_slices} slices, {retry_count} retr{'y' if retry_count == 1 else 'ies'} ({retry_detail}; others passed first try)"
        else:
            dispatches_str = f"{total_slices} slices, 0 retries (all passed first try)"
    else:
        total_slices = "(no data)"
        dispatches_str = "(no data)"

    # ------------------------------------------------------------------
    # Stages exercised / skipped
    # ------------------------------------------------------------------
    exercised = sorted({e.get("stage") for e in token_usage if e.get("stage")})
    skipped = [s for s in _KNOWN_STAGES if s not in exercised]
    exercised_str = ", ".join(exercised) if exercised else "(none)"
    skipped_str = ", ".join(skipped) if skipped else "(none)"

    # ------------------------------------------------------------------
    # Assemble
    # ------------------------------------------------------------------
    lines = [
        _RUN_FACTS_START,
        "",
        "### Wall clock",
        f"- Total: {total_str}",
        f"- Per stage: {per_stage_str}",
        "",
        "### Subprocess calls",
        f"- Codex: {codex_total} total ({codex_timeouts} timeout{'s' if codex_timeouts != 1 else ''}, {codex_other_errors} other error{'s' if codex_other_errors != 1 else ''}, {codex_parse_gaps} telemetry parse gap{'s' if codex_parse_gaps != 1 else ''})",
        f"- Gemini: {gemini_total} total ({gemini_errors} error{'s' if gemini_errors != 1 else ''}, {gemini_parse_gaps} telemetry parse gap{'s' if gemini_parse_gaps != 1 else ''})",
        "",
        "### Codex dispatches",
        f"- {dispatches_str}",
        "",
        "### Activity totals",
        f"- Stages exercised: {exercised_str}",
        f"- Stages skipped: {skipped_str}",
        "",
        _RUN_FACTS_END,
    ]
    return "\n".join(lines)


def _compose_generated_block(
    slug: str,
    pr_url: str,
    pr_number: int | None,
    merge_sha: str,
    closed_at: str,
    coverage: dict,
    token_usage: list[dict],
    codex_dispatches: list[dict],
) -> str:
    table = _coverage_table_text(coverage)
    pr_line = f"#{pr_number} — {pr_url}" if pr_number else (pr_url or "(not recorded)")
    sha_line = merge_sha or "(not recorded)"
    run_facts_body = _build_run_facts_text(token_usage, codex_dispatches)
    return "\n".join([
        f"# Closeout: {slug}",
        "",
        _GEN_START,
        "<!-- Editing the generated section will be overwritten on next closeout call. -->",
        "",
        "## Delivery",
        f"- PR: {pr_line}",
        f"- Merge SHA: {sha_line}",
        f"- Closed at: {closed_at}",
        "",
        "## Review Coverage",
        "",
        table,
        "",
        "## Run Facts",
        "",
        run_facts_body,
        "",
        _GEN_END,
    ])


def _compose_closeout_md(
    existing_text: str | None,
    slug: str,
    pr_url: str,
    pr_number: int | None,
    merge_sha: str,
    closed_at: str,
    coverage: dict,
    operator_note: str,
    token_usage: list[dict] | None = None,
    codex_dispatches: list[dict] | None = None,
) -> str:
    """Build closeout.md content, preserving the operator-notes section on re-run."""
    generated = _compose_generated_block(
        slug, pr_url, pr_number, merge_sha, closed_at, coverage,
        token_usage or [], codex_dispatches or [],
    )

    if existing_text:
        # Preserve everything after <!-- end-generated -->
        end_idx = existing_text.find(_GEN_END)
        if end_idx >= 0:
            after_marker = existing_text[end_idx + len(_GEN_END):].lstrip("\n")
            return generated + "\n\n" + after_marker if after_marker else generated
        # Old format without marker — append default operator-notes section
        # Extract anything that looks like "## Operator Notes" or later
        op_match = re.search(r"\n## Operator Notes.*", existing_text, re.DOTALL)
        if op_match:
            return generated + "\n" + op_match.group(0).lstrip("\n")

    # Fresh file: add empty operator-notes section
    note_section = f"\n## Operator Notes\n\n{operator_note}" if operator_note else "\n## Operator Notes\n\n"
    return generated + "\n" + note_section


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------


@mutates_state("closeout")
def command_standalone_closeout(args: argparse.Namespace) -> int:
    slug = args.slug
    root = workflow_dir(slug)
    state = load_workflow_state(slug)

    # Guard: refuse to run on an empty/no-FF state.
    # "Empty" means there is no meaningful runner activity recorded: no stages
    # were checkpointed, no AI calls were made, and no reviews exist on disk.
    # This indicates the slug was never actually run through the FF runner.
    has_stages = bool(state.get("stages"))
    has_token_usage = bool(state.get("token_usage"))
    reviews_exist = reviews_dir(slug).exists() and any(
        reviews_dir(slug).glob("*.review.md")
    )
    if not (has_stages or has_token_usage or reviews_exist):
        print(
            f"closeout: slug '{slug}' has no runner state (no discovery, stages, or token_usage). "
            "This slug was not run through the FF runner — no closeout record generated.",
            file=sys.stderr,
        )
        return 0

    # PR metadata — use provided args, fall back to gh CLI detection
    pr_url: str = getattr(args, "pr_url", None) or ""
    pr_number_raw = getattr(args, "pr_number", None)
    merge_sha: str = getattr(args, "merge_sha", None) or ""
    operator_note: str = getattr(args, "note", None) or ""
    out_path_raw: str | None = getattr(args, "out", None)

    pr_number: int | None = None
    if pr_number_raw is not None:
        try:
            pr_number = int(pr_number_raw)
        except (TypeError, ValueError):
            pr_number = None

    if not pr_url and not pr_number:
        branch_hint = _slug_to_branch(slug)
        detected = _detect_pr_from_gh(branch_hint)
        if detected:
            pr_url = pr_url or detected.get("pr_url", "")
            pr_number = pr_number or detected.get("pr_number")
            merge_sha = merge_sha or detected.get("merge_sha", "")

    closed_at = _iso_now()

    # Scan review files
    review_map = _scan_reviews(slug)
    token_usage = state.get("token_usage", []) if isinstance(state.get("token_usage"), list) else []
    codex_dispatches = state.get("codex_dispatches", []) if isinstance(state.get("codex_dispatches"), list) else []
    coverage = _build_review_coverage(review_map, token_usage)

    # Build coverage_summary for state.delivery
    coverage_summary: dict = {}
    for stage in ["spec", "plan", "tasks", "diff"]:
        data = coverage.get(stage, {})
        coverage_summary[f"{stage}_lenses_run"] = data.get("lenses_run", [])
        coverage_summary[f"{stage}_lenses_skipped"] = data.get("lenses_skipped", [])

    # Tick confirmed-merged slice checkboxes in tasks.md
    tasks_path = root / "tasks.md"
    _tick_merged_slices(tasks_path)

    # Determine output path
    if out_path_raw:
        out_path = Path(out_path_raw)
    else:
        out_path = root / "closeout.md"

    # Build closeout.md — preserve operator notes section on re-run
    existing_text: str | None = None
    if out_path.exists():
        existing_text = out_path.read_text(encoding="utf-8")

    closeout_text = _compose_closeout_md(
        existing_text,
        slug,
        pr_url,
        pr_number,
        merge_sha,
        closed_at,
        coverage,
        operator_note,
        token_usage=token_usage,
        codex_dispatches=codex_dispatches,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(closeout_text, encoding="utf-8")

    # Update state.delivery
    delivery_record = {
        "pr_url": pr_url,
        "pr_number": pr_number,
        "merge_sha": merge_sha,
        "closed_at": closed_at,
        "operator_note": operator_note,
        "review_coverage_summary": coverage_summary,
    }
    state[DELIVERY_KEY] = delivery_record
    save_workflow_state(slug, state)

    print(str(out_path))
    return 0
